//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobTelegramBot.ServiceHelper {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bankofbaku.com/PaymentService", ConfigurationName="ServiceHelper.TelegramBotHelperService")]
    public interface TelegramBotHelperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCurrencyRate" +
            "s", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCurrencyRate" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        BobTelegramBot.ServiceHelper.CurrencyRatesResult GetCurrencyRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCurrencyRate" +
            "s", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCurrencyRate" +
            "sResponse")]
        System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.CurrencyRatesResult> GetCurrencyRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/RegisterUserFee" +
            "dback", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/RegisterUserFee" +
            "dbackResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        BobTelegramBot.ServiceHelper.MobileBaseResult RegisterUserFeedback(string phoneNumber, BobTelegramBot.ServiceHelper.FeedbackMessage feedback, BobTelegramBot.ServiceHelper.KeyValueResult feedbackCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/RegisterUserFee" +
            "dback", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/RegisterUserFee" +
            "dbackResponse")]
        System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.MobileBaseResult> RegisterUserFeedbackAsync(string phoneNumber, BobTelegramBot.ServiceHelper.FeedbackMessage feedback, BobTelegramBot.ServiceHelper.KeyValueResult feedbackCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetBranchAndAtm" +
            "List", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetBranchAndAtm" +
            "ListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        BobTelegramBot.ServiceHelper.BranchAndAtmListResult GetBranchAndAtmList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetBranchAndAtm" +
            "List", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetBranchAndAtm" +
            "ListResponse")]
        System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.BranchAndAtmListResult> GetBranchAndAtmListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetFeedbackCate" +
            "gories", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetFeedbackCate" +
            "goriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        BobTelegramBot.ServiceHelper.KeyValueResult[] GetFeedbackCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetFeedbackCate" +
            "gories", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetFeedbackCate" +
            "goriesResponse")]
        System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.KeyValueResult[]> GetFeedbackCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCardsAndBran" +
            "ches", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCardsAndBran" +
            "chesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        BobTelegramBot.ServiceHelper.BobSiteCardAndBranchListResult GetCardsAndBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCardsAndBran" +
            "ches", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/GetCardsAndBran" +
            "chesResponse")]
        System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.BobSiteCardAndBranchListResult> GetCardsAndBranchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/OrderPlasticCar" +
            "d", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/OrderPlasticCar" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        BobTelegramBot.ServiceHelper.MobileBaseResult OrderPlasticCard(BobTelegramBot.ServiceHelper.BobSiteCardOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/OrderPlasticCar" +
            "d", ReplyAction="http://www.bankofbaku.com/PaymentService/TelegramBotHelperService/OrderPlasticCar" +
            "dResponse")]
        System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.MobileBaseResult> OrderPlasticCardAsync(BobTelegramBot.ServiceHelper.BobSiteCardOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class CurrencyRatesResult : MobileBaseResult {
        
        private IbCurrencyRate[] currencyRatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public IbCurrencyRate[] CurrencyRates {
            get {
                return this.currencyRatesField;
            }
            set {
                this.currencyRatesField = value;
                this.RaisePropertyChanged("CurrencyRates");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class IbCurrencyRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string currencyField;
        
        private double rateField;
        
        private double sellRateField;
        
        private double buyRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double SellRate {
            get {
                return this.sellRateField;
            }
            set {
                this.sellRateField = value;
                this.RaisePropertyChanged("SellRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double BuyRate {
            get {
                return this.buyRateField;
            }
            set {
                this.buyRateField = value;
                this.RaisePropertyChanged("BuyRate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class BobSiteCardOrderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cardIdField;
        
        private string orderTypeField;
        
        private int periodField;
        
        private string currencyField;
        
        private string nameField;
        
        private string surnameField;
        
        private string patronymicNameField;
        
        private string cardNameField;
        
        private string cardSurnameField;
        
        private string codeField;
        
        private PersonSex sexField;
        
        private string passportFrontField;
        
        private string passportBackField;
        
        private string passportNumberField;
        
        private string passportOrganField;
        
        private System.DateTime passportDateField;
        
        private System.DateTime birthDateField;
        
        private string regAddressField;
        
        private string livingAddressField;
        
        private string homePhoneField;
        
        private string mobilePhoneField;
        
        private string workPhoneField;
        
        private string emailField;
        
        private int branchIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
                this.RaisePropertyChanged("CardId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
                this.RaisePropertyChanged("Period");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PatronymicName {
            get {
                return this.patronymicNameField;
            }
            set {
                this.patronymicNameField = value;
                this.RaisePropertyChanged("PatronymicName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CardName {
            get {
                return this.cardNameField;
            }
            set {
                this.cardNameField = value;
                this.RaisePropertyChanged("CardName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CardSurname {
            get {
                return this.cardSurnameField;
            }
            set {
                this.cardSurnameField = value;
                this.RaisePropertyChanged("CardSurname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public PersonSex Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PassportFront {
            get {
                return this.passportFrontField;
            }
            set {
                this.passportFrontField = value;
                this.RaisePropertyChanged("PassportFront");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PassportBack {
            get {
                return this.passportBackField;
            }
            set {
                this.passportBackField = value;
                this.RaisePropertyChanged("PassportBack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PassportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
                this.RaisePropertyChanged("PassportNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PassportOrgan {
            get {
                return this.passportOrganField;
            }
            set {
                this.passportOrganField = value;
                this.RaisePropertyChanged("PassportOrgan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime PassportDate {
            get {
                return this.passportDateField;
            }
            set {
                this.passportDateField = value;
                this.RaisePropertyChanged("PassportDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string RegAddress {
            get {
                return this.regAddressField;
            }
            set {
                this.regAddressField = value;
                this.RaisePropertyChanged("RegAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LivingAddress {
            get {
                return this.livingAddressField;
            }
            set {
                this.livingAddressField = value;
                this.RaisePropertyChanged("LivingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("MobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
                this.RaisePropertyChanged("WorkPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int BranchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
                this.RaisePropertyChanged("BranchId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public enum PersonSex {
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyValueResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public abstract partial class BaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorCodes codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ErrorCodes code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public enum ErrorCodes {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        InvalidNumber,
        
        /// <remarks/>
        InvalidParameters,
        
        /// <remarks/>
        DublicatePaymentId,
        
        /// <remarks/>
        InvalidCurrency,
        
        /// <remarks/>
        InvalidUser,
        
        /// <remarks/>
        TransactionNotFound,
        
        /// <remarks/>
        StatusUnknown,
        
        /// <remarks/>
        NoSuchClientCode,
        
        /// <remarks/>
        RecordNotFound,
        
        /// <remarks/>
        TransactionNotCompleted,
        
        /// <remarks/>
        NotCorrectStatusPassed,
        
        /// <remarks/>
        NoCardFound,
        
        /// <remarks/>
        StillRegistered,
        
        /// <remarks/>
        NoOtpSetted,
        
        /// <remarks/>
        OtpIsNotValid,
        
        /// <remarks/>
        NoActiveSession,
        
        /// <remarks/>
        DailyTransactionCountExceeded,
        
        /// <remarks/>
        InvalidAmount,
        
        /// <remarks/>
        UnsuccessfulTransaction,
        
        /// <remarks/>
        TransactionAlreadyProcessed,
        
        /// <remarks/>
        DuplicateAuthCode,
        
        /// <remarks/>
        NoFoundAuthCode,
        
        /// <remarks/>
        UnknownError,
        
        /// <remarks/>
        SystemError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class KeyValueResult : BaseResult {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class FeedbackMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subjectField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class BobSiteCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cardIdField;
        
        private string cardTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
                this.RaisePropertyChanged("CardId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CardTitle {
            get {
                return this.cardTitleField;
            }
            set {
                this.cardTitleField = value;
                this.RaisePropertyChanged("CardTitle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class BobSiteBranch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string branchIdField;
        
        private string branchNameField;
        
        private string branchNameAzField;
        
        private string branchNameEnField;
        
        private string branchNameRuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BranchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
                this.RaisePropertyChanged("BranchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
                this.RaisePropertyChanged("BranchName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BranchNameAz {
            get {
                return this.branchNameAzField;
            }
            set {
                this.branchNameAzField = value;
                this.RaisePropertyChanged("BranchNameAz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BranchNameEn {
            get {
                return this.branchNameEnField;
            }
            set {
                this.branchNameEnField = value;
                this.RaisePropertyChanged("BranchNameEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BranchNameRu {
            get {
                return this.branchNameRuField;
            }
            set {
                this.branchNameRuField = value;
                this.RaisePropertyChanged("BranchNameRu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class PaymentTerminal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private MultiLanguageString titleField;
        
        private MultiLanguageString descField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MultiLanguageString Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MultiLanguageString Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class MultiLanguageString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string azField;
        
        private string enField;
        
        private string ruField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Az {
            get {
                return this.azField;
            }
            set {
                this.azField = value;
                this.RaisePropertyChanged("Az");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string En {
            get {
                return this.enField;
            }
            set {
                this.enField = value;
                this.RaisePropertyChanged("En");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ru {
            get {
                return this.ruField;
            }
            set {
                this.ruField = value;
                this.RaisePropertyChanged("Ru");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class Atm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private MultiLanguageString titleField;
        
        private MultiLanguageString descField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MultiLanguageString Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MultiLanguageString Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class Branch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private MultiLanguageString titleField;
        
        private MultiLanguageString descField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MultiLanguageString Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MultiLanguageString Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BobSiteCardAndBranchListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BranchAndAtmListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrencyRatesResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class MobileBaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultCode codeField;
        
        private string messageField;
        
        private AsanResultCode asanResultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultCode Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AsanResultCode AsanResultCode {
            get {
                return this.asanResultCodeField;
            }
            set {
                this.asanResultCodeField = value;
                this.RaisePropertyChanged("AsanResultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public enum ResultCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        InvalidData,
        
        /// <remarks/>
        DeviceNotFound,
        
        /// <remarks/>
        NoMobile,
        
        /// <remarks/>
        InvalidSid,
        
        /// <remarks/>
        OtpDailyLimitExceeded,
        
        /// <remarks/>
        AccountLocked,
        
        /// <remarks/>
        AccountTemporarilyBlocked,
        
        /// <remarks/>
        AsanError,
        
        /// <remarks/>
        AsanOutstandingTransaction,
        
        /// <remarks/>
        AsanSignatureCreated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public enum AsanResultCode {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        InternalError,
        
        /// <remarks/>
        UserAuthenticated,
        
        /// <remarks/>
        InvalidParameters,
        
        /// <remarks/>
        NoAuthCertificate,
        
        /// <remarks/>
        NoSignCertificate,
        
        /// <remarks/>
        PhoneIdMismatch,
        
        /// <remarks/>
        ServiceOverload,
        
        /// <remarks/>
        InvalidSignCertificate,
        
        /// <remarks/>
        InvalidPhoneNumber,
        
        /// <remarks/>
        ExpiredTransaction,
        
        /// <remarks/>
        InvalidSign,
        
        /// <remarks/>
        PhoneUnreachable,
        
        /// <remarks/>
        ProcessError,
        
        /// <remarks/>
        SimError,
        
        /// <remarks/>
        UserCancel,
        
        /// <remarks/>
        CheckPhone,
        
        /// <remarks/>
        FillFields,
        
        /// <remarks/>
        AuthCertificateInvalid,
        
        /// <remarks/>
        OutstandingTransaction,
        
        /// <remarks/>
        MidNotReady,
        
        /// <remarks/>
        NotValid,
        
        /// <remarks/>
        SendError,
        
        /// <remarks/>
        SignatureCreated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class BobSiteCardAndBranchListResult : MobileBaseResult {
        
        private BobSiteBranch[] bobSiteBranchListField;
        
        private BobSiteCard[] bobSiteCardListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public BobSiteBranch[] BobSiteBranchList {
            get {
                return this.bobSiteBranchListField;
            }
            set {
                this.bobSiteBranchListField = value;
                this.RaisePropertyChanged("BobSiteBranchList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public BobSiteCard[] BobSiteCardList {
            get {
                return this.bobSiteCardListField;
            }
            set {
                this.bobSiteCardListField = value;
                this.RaisePropertyChanged("BobSiteCardList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bankofbaku.com/PaymentService")]
    public partial class BranchAndAtmListResult : MobileBaseResult {
        
        private Branch[] branchListField;
        
        private Atm[] atmListField;
        
        private PaymentTerminal[] paymentTerminalListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Branch[] BranchList {
            get {
                return this.branchListField;
            }
            set {
                this.branchListField = value;
                this.RaisePropertyChanged("BranchList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Atm[] AtmList {
            get {
                return this.atmListField;
            }
            set {
                this.atmListField = value;
                this.RaisePropertyChanged("AtmList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public PaymentTerminal[] PaymentTerminalList {
            get {
                return this.paymentTerminalListField;
            }
            set {
                this.paymentTerminalListField = value;
                this.RaisePropertyChanged("PaymentTerminalList");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TelegramBotHelperServiceChannel : BobTelegramBot.ServiceHelper.TelegramBotHelperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelegramBotHelperServiceClient : System.ServiceModel.ClientBase<BobTelegramBot.ServiceHelper.TelegramBotHelperService>, BobTelegramBot.ServiceHelper.TelegramBotHelperService {
        
        public TelegramBotHelperServiceClient() {
        }
        
        public TelegramBotHelperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TelegramBotHelperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelegramBotHelperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelegramBotHelperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BobTelegramBot.ServiceHelper.CurrencyRatesResult GetCurrencyRates() {
            return base.Channel.GetCurrencyRates();
        }
        
        public System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.CurrencyRatesResult> GetCurrencyRatesAsync() {
            return base.Channel.GetCurrencyRatesAsync();
        }
        
        public BobTelegramBot.ServiceHelper.MobileBaseResult RegisterUserFeedback(string phoneNumber, BobTelegramBot.ServiceHelper.FeedbackMessage feedback, BobTelegramBot.ServiceHelper.KeyValueResult feedbackCategory) {
            return base.Channel.RegisterUserFeedback(phoneNumber, feedback, feedbackCategory);
        }
        
        public System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.MobileBaseResult> RegisterUserFeedbackAsync(string phoneNumber, BobTelegramBot.ServiceHelper.FeedbackMessage feedback, BobTelegramBot.ServiceHelper.KeyValueResult feedbackCategory) {
            return base.Channel.RegisterUserFeedbackAsync(phoneNumber, feedback, feedbackCategory);
        }
        
        public BobTelegramBot.ServiceHelper.BranchAndAtmListResult GetBranchAndAtmList() {
            return base.Channel.GetBranchAndAtmList();
        }
        
        public System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.BranchAndAtmListResult> GetBranchAndAtmListAsync() {
            return base.Channel.GetBranchAndAtmListAsync();
        }
        
        public BobTelegramBot.ServiceHelper.KeyValueResult[] GetFeedbackCategories() {
            return base.Channel.GetFeedbackCategories();
        }
        
        public System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.KeyValueResult[]> GetFeedbackCategoriesAsync() {
            return base.Channel.GetFeedbackCategoriesAsync();
        }
        
        public BobTelegramBot.ServiceHelper.BobSiteCardAndBranchListResult GetCardsAndBranches() {
            return base.Channel.GetCardsAndBranches();
        }
        
        public System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.BobSiteCardAndBranchListResult> GetCardsAndBranchesAsync() {
            return base.Channel.GetCardsAndBranchesAsync();
        }
        
        public BobTelegramBot.ServiceHelper.MobileBaseResult OrderPlasticCard(BobTelegramBot.ServiceHelper.BobSiteCardOrderRequest request) {
            return base.Channel.OrderPlasticCard(request);
        }
        
        public System.Threading.Tasks.Task<BobTelegramBot.ServiceHelper.MobileBaseResult> OrderPlasticCardAsync(BobTelegramBot.ServiceHelper.BobSiteCardOrderRequest request) {
            return base.Channel.OrderPlasticCardAsync(request);
        }
    }
}
