//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobTelegramBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BobTelegramBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All list.
        /// </summary>
        internal static string AllList {
            get {
                return ResourceManager.GetString("AllList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        internal static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast was stopped.
        /// </summary>
        internal static string BroadcastStopped {
            get {
                return ResourceManager.GetString("BroadcastStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Rate.
        /// </summary>
        internal static string BuyRate {
            get {
                return ResourceManager.GetString("BuyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find you. Do have credit account in our bank?.
        /// </summary>
        internal static string CantFindYou {
            get {
                return ResourceManager.GetString("CantFindYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you completed the quest! Your data is transferred to the appropriate bank structures and the answer will not take long time to wait.
        /// </summary>
        internal static string CardOrdered {
            get {
                return ResourceManager.GetString("CardOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card request.
        /// </summary>
        internal static string CardRequest {
            get {
                return ResourceManager.GetString("CardRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In.
        /// </summary>
        internal static string CashIn {
            get {
                return ResourceManager.GetString("CashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Name: {0}
        ///Credit number: {1}
        ///Create date: {2}
        ///Total credit amount: {3} {4}
        ///Total amount left: {5} {4}
        ///Amount to pay: {6} {4}.
        /// </summary>
        internal static string CreditInfo {
            get {
                return ResourceManager.GetString("CreditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of your credits.
        /// </summary>
        internal static string CreditList {
            get {
                return ResourceManager.GetString("CreditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit request.
        /// </summary>
        internal static string CreditRequest {
            get {
                return ResourceManager.GetString("CreditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency calculator.
        /// </summary>
        internal static string CurrencyCalculator {
            get {
                return ResourceManager.GetString("CurrencyCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rates.
        /// </summary>
        internal static string CurrencyRates {
            get {
                return ResourceManager.GetString("CurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}
        ///Please enter command or /help for command list.
        /// </summary>
        internal static string DefaultMessage {
            get {
                return ResourceManager.GetString("DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have registered credits.
        /// </summary>
        internal static string DontHaveCredits {
            get {
                return ResourceManager.GetString("DontHaveCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your birthday 
        ///(DD.MM.YYYY, ex. 01.01.1900).
        /// </summary>
        internal static string EnterBirthdate {
            get {
                return ResourceManager.GetString("EnterBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select branch.
        /// </summary>
        internal static string EnterBranch {
            get {
                return ResourceManager.GetString("EnterBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your client ID (client code).
        /// </summary>
        internal static string EnterClientId {
            get {
                return ResourceManager.GetString("EnterClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select credit card type.
        /// </summary>
        internal static string EnterCreditCardType {
            get {
                return ResourceManager.GetString("EnterCreditCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        internal static string EnterCurrency {
            get {
                return ResourceManager.GetString("EnterCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your feedback in single message.
        /// </summary>
        internal static string EnterFeedback {
            get {
                return ResourceManager.GetString("EnterFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your FirstName.
        /// </summary>
        internal static string EnterFirstname {
            get {
                return ResourceManager.GetString("EnterFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter home phone number.
        /// </summary>
        internal static string EnterHomePhone {
            get {
                return ResourceManager.GetString("EnterHomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Lastname.
        /// </summary>
        internal static string EnterLastname {
            get {
                return ResourceManager.GetString("EnterLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter lastname on card (only English letters, please).
        /// </summary>
        internal static string EnterLastNameOnCard {
            get {
                return ResourceManager.GetString("EnterLastNameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter living address or type &quot;same&quot;.
        /// </summary>
        internal static string EnterLivingAdress {
            get {
                return ResourceManager.GetString("EnterLivingAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name on card (only English letters, please).
        /// </summary>
        internal static string EnterNameOnCard {
            get {
                return ResourceManager.GetString("EnterNameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select order type.
        /// </summary>
        internal static string EnterOrderType {
            get {
                return ResourceManager.GetString("EnterOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send photo of back side of your passport (Şəxsiyyət vəsiqəsi).
        /// </summary>
        internal static string EnterPassportBack {
            get {
                return ResourceManager.GetString("EnterPassportBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your passport date 
        ///(DD.MM.YYYY, ex. 01.01.1900).
        /// </summary>
        internal static string EnterPassportDate {
            get {
                return ResourceManager.GetString("EnterPassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send photo of front side of your passport (Şəxsiyyət vəsiqəsi).
        /// </summary>
        internal static string EnterPassportFront {
            get {
                return ResourceManager.GetString("EnterPassportFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter passport number (Şəxsiyyət vəsiqəsi).
        /// </summary>
        internal static string EnterPassportNumber {
            get {
                return ResourceManager.GetString("EnterPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter passport authority organization.
        /// </summary>
        internal static string EnterPassportOrgan {
            get {
                return ResourceManager.GetString("EnterPassportOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you Patronymic Name.
        /// </summary>
        internal static string EnterPatronymicName {
            get {
                return ResourceManager.GetString("EnterPatronymicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select period.
        /// </summary>
        internal static string EnterPeriod {
            get {
                return ResourceManager.GetString("EnterPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter registration address.
        /// </summary>
        internal static string EnterRegistrationAddress {
            get {
                return ResourceManager.GetString("EnterRegistrationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter secret word (only 10 letters max).
        /// </summary>
        internal static string EnterSecretWord {
            get {
                return ResourceManager.GetString("EnterSecretWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your sex.
        /// </summary>
        internal static string EnterSex {
            get {
                return ResourceManager.GetString("EnterSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value.
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter work phone number.
        /// </summary>
        internal static string EnterWorkPhone {
            get {
                return ResourceManager.GetString("EnterWorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while sending message. Please, try again later.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback saved!.
        /// </summary>
        internal static string FeedbackSaved {
            get {
                return ResourceManager.GetString("FeedbackSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments.
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birthday.
        /// </summary>
        internal static string InvalidBirthdate {
            get {
                return ResourceManager.GetString("InvalidBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client ID.
        /// </summary>
        internal static string InvalidClientId {
            get {
                return ResourceManager.GetString("InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data, please try again.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is big, max allow filesize is {0} Kb..
        /// </summary>
        internal static string InvalidFilesize {
            get {
                return ResourceManager.GetString("InvalidFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key.
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response received.
        /// </summary>
        internal static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string MyCredits {
            get {
                return ResourceManager.GetString("MyCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        internal static string Nearest {
            get {
                return ResourceManager.GetString("Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t found your location. Please, enable GPS.
        /// </summary>
        internal static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t found nearest places around you.
        /// </summary>
        internal static string NoNearestLocation {
            get {
                return ResourceManager.GetString("NoNearestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year.
        /// </summary>
        internal static string OneYear {
            get {
                return ResourceManager.GetString("OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast order (+15 AZN).
        /// </summary>
        internal static string OrderFast {
            get {
                return ResourceManager.GetString("OrderFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string OrderNormal {
            get {
                return ResourceManager.GetString("OrderNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string PageNavigation {
            get {
                return ResourceManager.GetString("PageNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay credit.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        internal static string PlasticCardRequestStep {
            get {
                return ResourceManager.GetString("PlasticCardRequestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev..
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request saved.
        /// </summary>
        internal static string RequestSaved {
            get {
                return ResourceManager.GetString("RequestSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response received.
        /// </summary>
        internal static string ResponseReceived {
            get {
                return ResourceManager.GetString("ResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select *BUY* currency.
        /// </summary>
        internal static string SelectBuyCurrency {
            get {
                return ResourceManager.GetString("SelectBuyCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select *SELL* currency.
        /// </summary>
        internal static string SelectSellCurrency {
            get {
                return ResourceManager.GetString("SelectSellCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select send type.
        /// </summary>
        internal static string SelectSendType {
            get {
                return ResourceManager.GetString("SelectSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type.
        /// </summary>
        internal static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Rate.
        /// </summary>
        internal static string SellRate {
            get {
                return ResourceManager.GetString("SellRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to send a request for a credit for number {0}?.
        /// </summary>
        internal static string SendCreditRequest {
            get {
                return ResourceManager.GetString("SendCreditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Telegram.
        /// </summary>
        internal static string SendMessageDisable {
            get {
                return ResourceManager.GetString("SendMessageDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all msg via SMS and Telegram.
        /// </summary>
        internal static string SendMessagesBoth {
            get {
                return ResourceManager.GetString("SendMessagesBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all messages to Telegram.
        /// </summary>
        internal static string SendMessagesTelegram {
            get {
                return ResourceManager.GetString("SendMessagesTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me your phone number.
        /// </summary>
        internal static string SendPhoneNumber {
            get {
                return ResourceManager.GetString("SendPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three years.
        /// </summary>
        internal static string ThreeYear {
            get {
                return ResourceManager.GetString("ThreeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many feedbacks. Try again tomorrow.
        /// </summary>
        internal static string TooManyFeedbacks {
            get {
                return ResourceManager.GetString("TooManyFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two years.
        /// </summary>
        internal static string TwoYear {
            get {
                return ResourceManager.GetString("TwoYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are collectiong all data. Please wait.
        /// </summary>
        internal static string WaitAMoment {
            get {
                return ResourceManager.GetString("WaitAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Broadcast!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
